return {
	legmando = {
		maxacc = 0.805,
		activatewhenbuilt = true,
		autoheal = 18,
		maxdec = 3.45,
		energycost = 31000,
		metalcost = 1800,
		builddistance = 275,
		builder = true,
		buildpic = "CORMANDO.DDS",
		buildtime = 17100,
		canassist = true,
		canmove = true,
		canreclaim = true,
		canrepair = true,
		canrestore = true,
		canresurrect = true,
		category = "ALL MOBILE WEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE BOT CANBEUW EMPABLE",
		cancloak = true,
		initcloaked = true,
		cloakcost = 20,
		cloakcostmoving = 200,
		mincloakdistance = 75,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "38 50 22",
		collisionvolumetype = "box",
		metalstorage = 5,
		energymake = 20,
		energystorage = 50,
		explodeas = "mediumexplosiongeneric",
		footprintx = 2,
		footprintz = 2,
		idleautoheal = 36,
		idletime = 450,
		health = 3120,
		maxslope = 40,
		speed = 110.0,
		movementclass = "ABOT2",
		nochasecategory = "VTOL",
		objectname = "Units/CORMANDO.s3o",
		radardistance = 1350,
		radardistancejam = 300,
		script = "Units/CORMANDO.cob",
		seismicsignature = 2,
		selfdestructas = "mediumExplosionGenericSelfd",
		sightdistance = 900,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 1.65,
		turnrate = 2336.80002,
		upright = true,
		workertime = 400,
		buildoptions = {
			[1] = "corvalk",
			[2] = "legfig",
			[3] = "cormine4",
			[4] = "legdtl",
			[5] = "legforti",
			[6] = "corrl",
			[7] = "corjamt",
			[8] = "cortl",
			[9] = "legmex",
			[10] = "legnanotct2",
			[11] = "legck",
			[12] = "leggob",
			[13] = "leggat",
			[14] = "leginfestor",
			[15] = "legsrail",
			[16] = "legkam",
		},
		customparams = {
			unitgroup = 'buildert2',
			model_author = "FireStorm",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "corbots/t2",
			techlevel = 2,
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-small",
				[2] = "custom:radarpulse_t1",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			build = "nanlath2",
			canceldestruct = "cancel2",
			capture = "capture2",
			repair = "repair2",
			underattack = "warning1",
			working = "reclaim1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "kbcormov",
			},
			select = {
				[1] = "kbcorsel",
			},
		},
		weapondefs = {
			commando_blaster = {
				accuracy = 120,
				areaofeffect = 70,
				avoidfeature = false,
				craterareaofeffect = 70,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 100,
				gravityaffected = "true",
				impulseboost = 0,
				impulsefactor = 0,
				name = "CommandoBlaster",
				noselfdamage = true,
				predictboost = 0.5,
				proximitypriority = -10,
				range = 600,
				reloadtime = 0.25,
				rgbcolor = "0.85,0.3,0.2",
				soundhit = "xplosml5",
				soundhitwet = "sizzle",
				soundstart = "lasrfir5",
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 1860,
				damage = {
					default = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "COMMANDO_BLASTER",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
}
