return {
	leggant = {
		maxacc = 0,
		maxdec = 0,
		energycost = 95000, --62000 x1		+		: legadvos = 33000 x1
		metalcost = 10920, --8400 x1		+		: legadvos = 2520 x1
		builder = true,
		buildpic = "LEGGANT.DDS",
		buildtime = 87721, --67321			+		: legadvos = 20400 x1
		canmove = true,
		category = "ALL NOTLAND NOWEAPON NOTSUB NOTSHIP NOTAIR NOTHOVER SURFACE EMPABLE",
		collisionvolumeoffsets = "0 -5 8",
		collisionvolumescales = "150 43 150",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energystorage = 81400, --1400		+		: legadvos = 80000 x1
		explodeas = "hugeBuildingexplosiongeneric",
		footprintx = 9,
		footprintz = 9,
		idleautoheal = 25, --5
		idletime = 900, --1800
		health = 43200, --17800				+		: legadvos = 25400 x1
		maxslope = 10,
		maxwaterdepth = 0,
		metalstorage = 20800, --800			+		: legadvos = 20000 x1
		objectname = "Units/CORGANT.s3o",
		radardistance = 50,
		script = "Units/CORGANT.cob",
		seismicsignature = 0,
		selfdestructas = "hugeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		terraformspeed = 3000,
		usepiececollisionvolumes = 1,
		workertime = 1800, --600
		yardmap = "oooooooooooooooooooocccccoooocccccoooocccccoooocccccoooocccccoooocccccoooocccccoo",
		buildoptions = {
			[1] = "corkorg",
			[2] = "corkarg",
			[3] = "corjugg",
			[4] = "corshiva",
			[5] = "corcat",
			[6] = "corsok",
			[7] = "legpede",
			[8] = "leegmech",
			[9] = "legkeres",
			[10] = "legaca", --n/a
			[11] = "legcrwt4",
			[12] = "armvadert4",
			[13] = "corgolt4",
			[14] = "corkarganetht4",
			[15] = "corthermite",
			[16] = "armthundt4",
			[17] = "corfblackhyt4",
		},
		customparams = {
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/corgant_aoplane.dds",
			buildinggrounddecalsizey = 12,
			buildinggrounddecalsizex = 12,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'buildert3',
			model_author = "Mr Bob",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "corbuildings/landfactories",
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0 -21 0",
				collisionvolumescales = "114 74 129",
				collisionvolumetype = "CylZ",
				damage = 9600,
				featuredead = "HEAP",
				footprintx = 9,
				footprintz = 9,
				height = 20,
				metal = 5101,
				object = "Units/corgant_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 4800,
				footprintx = 9,
				footprintz = 9,
				height = 4,
				metal = 2040,
				object = "Units/cor7X7B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:GantWhiteLight",
				[2] = "custom:YellowLight",
				[3] = "custom:WhiteLight",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg3",
				[2] = "deathceg4",
			},
		},
		sounds = {
			activate = "gantok2",
			build = "gantok2",
			canceldestruct = "cancel2",
			deactivate = "gantok2",
			repair = "lathelrg",
			underattack = "warning1",
			unitcomplete = "gantok1",
			working = "build",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "gantsel1",
			},
		},
	},
}
